import { PlanConfig } from '../types';

export const STANDARD_PLANS: PlanConfig[] = [
  {
    plan_id: 'free',
    plan_name: 'FREE',
    nameMarathi: 'मोफत प्लॅन',
    price: 0,
    originalPrice: 0,
    billing_cycle: 'free',
    periodLabel: 'Forever Free',
    periodLabelMarathi: 'कायमस्वरूपी मोफत',
    business_limit: 1,
    team_member_limit: 0,
    poster_limit: -1,
    features: [
      '3 watermark-free posters every month',
      'After 3 free posters → unlimited poster creation with GROW VIEW watermark',
      'No premium features',
      'No premium templates',
      'No premium export',
    ],
    watermark_status: 'WATERMARK_AFTER_3_FREE',
    is_active: true,
    display_order: 1,
    description: 'Start creating festivals and business posters for free.',
    button_text: 'CURRENT PLAN',
    badge: 'FREE FOREVER',
    is_popular: false,
    highlight_text: '3 FREE WATERMARK-FREE POSTERS EVERY MONTH',
    premium_access: false,
    premium_templates: false,
    premium_export: false,
  },
  {
    plan_id: 'starter-monthly',
    plan_name: 'STARTER MONTHLY',
    nameMarathi: 'स्टार्टर मासिक',
    price: 99,
    originalPrice: 249,
    billing_cycle: 'monthly',
    periodLabel: '/ Month',
    periodLabelMarathi: '/ महिना',
    business_limit: 1,
    team_member_limit: 0,
    poster_limit: -1,
    features: [
      '1 Business',
      'Premium access',
      'No GROW VIEW watermark',
      'Premium templates',
      'Premium export',
    ],
    watermark_status: 'NO_WATERMARK',
    is_active: true,
    display_order: 2,
    description: 'Perfect for single business owners and freelancers.',
    button_text: 'BUY NOW',
    badge: 'STARTER',
    is_popular: false,
    highlight_text: 'NO GROW VIEW WATERMARK',
    premium_access: true,
    premium_templates: true,
    premium_export: true,
  },
  {
    plan_id: 'business-monthly',
    plan_name: 'BUSINESS MONTHLY',
    nameMarathi: 'बिझनेस मासिक',
    price: 299,
    originalPrice: 599,
    billing_cycle: 'monthly',
    periodLabel: '/ Month',
    periodLabelMarathi: '/ महिना',
    business_limit: 5,
    team_member_limit: 0,
    poster_limit: -1,
    features: [
      'Up to 5 Businesses',
      'Premium access',
      'No GROW VIEW watermark',
      'Premium templates',
      'Premium export',
      'Multiple business profiles',
    ],
    watermark_status: 'NO_WATERMARK',
    is_active: true,
    display_order: 3,
    description: 'Ideal for entrepreneurs managing multiple business brands.',
    button_text: 'BUY NOW',
    badge: 'MULTI-BRAND',
    is_popular: false,
    highlight_text: 'NO GROW VIEW WATERMARK',
    premium_access: true,
    premium_templates: true,
    premium_export: true,
  },
  {
    plan_id: 'starter-yearly',
    plan_name: 'STARTER YEARLY',
    nameMarathi: 'स्टार्टर वार्षिक',
    price: 599,
    originalPrice: 1199,
    billing_cycle: 'yearly',
    periodLabel: '/ Year',
    periodLabelMarathi: '/ वर्ष (₹50/महिना)',
    business_limit: 1,
    team_member_limit: 0,
    poster_limit: -1,
    features: [
      '1 Business',
      'Premium access',
      'No GROW VIEW watermark',
      'Premium templates',
      'Premium export',
    ],
    watermark_status: 'NO_WATERMARK',
    is_active: true,
    display_order: 4,
    description: '365 days of uninterrupted watermark-free branding.',
    button_text: 'BUY NOW',
    badge: 'BEST SELLER',
    is_popular: true,
    highlight_text: 'NO GROW VIEW WATERMARK',
    premium_access: true,
    premium_templates: true,
    premium_export: true,
  },
  {
    plan_id: 'business-yearly',
    plan_name: 'BUSINESS YEARLY',
    nameMarathi: 'बिझनेस वार्षिक',
    price: 1199,
    originalPrice: 2499,
    billing_cycle: 'yearly',
    periodLabel: '/ Year',
    periodLabelMarathi: '/ वर्ष (₹100/महिना)',
    business_limit: 5,
    team_member_limit: 0,
    poster_limit: -1,
    features: [
      'Up to 5 Businesses',
      'Premium access',
      'No GROW VIEW watermark',
      'Premium templates',
      'Premium export',
      'Multiple business profiles',
    ],
    watermark_status: 'NO_WATERMARK',
    is_active: true,
    display_order: 5,
    description: 'Maximum savings for established multi-brand businesses.',
    button_text: 'BUY NOW',
    badge: 'BEST VALUE',
    is_popular: false,
    highlight_text: 'NO GROW VIEW WATERMARK',
    premium_access: true,
    premium_templates: true,
    premium_export: true,
  },
];

export const BUSINESS_TEAM_PLAN: PlanConfig = {
  plan_id: 'business-team',
  plan_name: 'BUSINESS / TEAM',
  nameMarathi: 'बिझनेस / टीम',
  price: 0,
  originalPrice: 0,
  billing_cycle: 'custom',
  periodLabel: 'CUSTOM PRICING',
  periodLabelMarathi: 'कस्टम दर',
  business_limit: 15,
  team_member_limit: 20,
  poster_limit: -1,
  features: [
    'For 10–20+ team members',
    'Multiple business profiles & branding',
    'Admin dashboard & member role control',
    'No GROW VIEW watermark',
    'Premium templates & 4K exports',
    'Dedicated priority support',
  ],
  watermark_status: 'NO_WATERMARK',
  is_active: true,
  display_order: 6,
  description: 'Need GROW VIEW for your entire team? For businesses, agencies and organizations with 10–20+ team members.',
  button_text: 'CONTACT US',
  badge: 'ENTERPRISE & AGENCIES',
  is_popular: false,
  highlight_text: 'FOR 10–20+ TEAM MEMBERS',
  premium_access: true,
  premium_templates: true,
  premium_export: true,
};

export function getPlanConfigById(planId: string, availablePlans: PlanConfig[] = STANDARD_PLANS): PlanConfig {
  if (planId === 'business-team') return BUSINESS_TEAM_PLAN;
  const found = availablePlans.find((p) => p.plan_id === planId);
  return found || STANDARD_PLANS[0];
}

export function formatPlanPrice(plan: PlanConfig): string {
  if (plan.billing_cycle === 'free') return '₹0';
  if (plan.billing_cycle === 'custom') return 'CUSTOM PRICING';
  return `₹${plan.price}${plan.billing_cycle === 'monthly' ? '/month' : '/year'}`;
}
